services:
  - type: web
    name: adaptive-math-simple
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
    
    # Run DB migrations after each deploy (safe if no migrations pending)
    postDeployCommand: |
      export FLASK_APP=wsgi.py
      flask db upgrade
